### PR TITLE
Mongo Update

### PR DESCRIPTION
**Pull request by bearburger**
Hi. I've fixed your code to work with MongoDB. I've changed my bid on UP to 1 hour price. Hope you are fair person :-) Not sure if this is not against UP TOS so keep names empty. You didn't interviewed me so far.

### CODE REVIEW

**Comment by xDarkicex** [comment]
confused?

**Review by xDarkicex — COMMENTED** [review]
okay why?

**Comment by bearburger** [comment]
@xDarkicex not confused. Just don't want this PR to be shown as +1 in top menu. If I found your profile, then other freelancers can too. They may be interested what means 1 PR to such personal project. And UP rules are against any form of "free" work, even if, well, I was bored enough to just fix this, even if you wouldn't pay in final :-) So these freelancers could just report my account for breaking TOS. So if you can, just manually copy changes to your code and remove this PR from history. Yeh, paranoid but this is UP and they are crazy about possible lost profit.

**Comment by xDarkicex** [comment]
I am glad to help I just honestly dont know what you mean by +1 PR what is this?

**Comment by bearburger** [comment]
@xDarkicex counter in top menu shows number of open pull requests (PR) (http://i.imgur.com/O33TTTC.png). So I just closed it. And I found that you can't completely remove pull requests even as owner so let's keep it as it is.

**Pull request closed without merging**
